services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1032:65536 # jellyfin:mediaman
    volumes:
      - /volume1/docker/jellyfin/config:/config
      - /volume1/docker/jellyfin/cache:/cache
      - type: bind
        source: /volume2/media
        target: /media
      - type: bind
        source: /volume3/media02
        target: /media02
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8096:8096
    environment:    
      - GIDLIST=937 # videodriver GID
      #- TZ=Europe/Zurich
      #- DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel	  
    # Optional - alternative address used for autodiscovery environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.triky.net      
    restart: 'unless-stopped'
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'